import { Inter } from "next/font/google";
import { Layout, Menu } from "antd";
import AdminHeader from "@/components/admin/AdminHeader";
import Sider from "antd/es/layout/Sider";
import AppSideMenu from "@/components/admin/AppSideMenu";
import { Content } from "antd/es/layout/layout";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <>
      <Layout>
        <Sider theme="light" width={200} className="site-layout-background">
          <AppSideMenu />
        </Sider>
        <Layout className="site-layout">
          <Content
            style={{
              margin: '24px 16px',
              padding: 24,
              height: '52rem',
              background: '#fff',
              overflow: 'auto',
            }}
          >
            {children}
          </Content>

        </Layout>
      </Layout>
    </>
  );
}